# Generated by Django 3.0.5 on 2020-04-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
